"use client";

import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'my';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        "profile.title": "Profile Settings",
        "profile.subtitle": "Manage your account information and preferences.",
        "profile.photo": "Your Photo",
        "profile.change": "Change",
        "profile.delete": "Delete",
        "profile.name": "Full Name",
        "profile.email": "Email Address",
        "profile.language": "Language",
        "profile.save": "Save Details",
        "profile.signout": "Sign Out",
        "profile.signout_desc": "Sign out of your account on this device.",
        "profile.role": "Role",
        "profile.joined": "Joined",
        "nav.dashboard": "Dashboard",
        "nav.patients": "Patients",
        "nav.chat": "Chat",
        "nav.schedule": "Schedules",
        "nav.profile": "Profile",
        "nav.overview": "Family",
        "nav.appointments": "Appointments",
        "nav.reports": "Reports",
        "nav.services": "Services",
        "nav.view_profile": "View profile",
        "nav.sign_out": "Sign Out",
        "chat.search": "Search connections...",
        "chat.no_connections_title": "No care connections yet",
        "chat.no_connections_desc": "Once a carer is assigned to your family member, they will appear here and you can start chatting with them.",
        "chat.select_prompt": "Select a care connection to start chatting",
        "chat.online": "Online",
        "chat.type_message": "Type your message...",
        "chat.video": "Video",
        "schedule.empty": "No scheduled appointments yet.",
        "common.loading": "Loading...",
        "common.error": "An error occurred",
        "carer.specialty": "Specialty",
        "carer.experience": "Years of Experience",
        "carer.verified": "Verified Carer",
        "carer.pending": "Verification Pending",
        "carer.title": "Professional Carer",
        "patients.search_placeholder": "Search patients...",
        "patients.none_assigned": "No patients assigned",
        "patients.contact_admin": "Contact your administrator to get assigned to patients.",
        "patients.no_match": "No matching patients found",
        "patients.patient": "Patient",
        "patients.location": "Location",
        "patients.records_meds": "Records & Meds",
        "patients.records": "Records",
        "patients.meds": "Meds",
        "carer.dashboard.patients": "Patients",
        "carer.dashboard.records": "Records",
        "carer.dashboard.visits": "Visits",
        "carer.dashboard.my_patients": "My Patients",
        "carer.dashboard.view_all": "View All",
        "carer.dashboard.quick_actions": "Quick Actions",
        "carer.dashboard.log_vitals": "Log Vitals",
        "carer.dashboard.schedule": "Schedule",
        "schedules.upcoming": "Upcoming",
        "schedules.calendar": "Calendar",
        "schedules.history": "History",
        "schedules.no_upcoming": "No upcoming schedules",
        "schedules.no_history": "No history",
        "schedules.none_for_date": "No visits scheduled for this date.",
        "reports.title": "Digital Reports",
        "reports.filter.all": "All Reports",
        "reports.filter.weekly": "Weekly Summaries",
        "reports.empty.title": "No reports",
        "reports.empty.desc": "You don't have any reports yet.",
        "family.core.title": "Core plan features",
        "family.core.subtitle": "Included with your 990 THB plan.",
        "family.feature.health_monitor": "Health Monitor",
        "family.feature.health_monitor_desc": "Track vitals and trends.",
        "family.feature.view": "View",
        "family.feature.reminders": "Reminders",
        "family.feature.reminders_desc": "Track daily meds.",
        "family.feature.schedule": "Schedule",
        "family.feature.reports": "Reports",
        "family.feature.reports_desc": "Weekly care summaries.",
        "family.feature.chat": "Care Chat",
        "family.feature.chat_desc": "Chat with your carer.",
        "family.feature.message": "Message",
        "family.feature.checkups": "Checkups",
        "family.feature.checkups_desc": "Track home visits.",
        "family.feature.settings": "Settings",
        "family.feature.burmese_ui": "Burmese UI",
        "family.feature.burmese_ui_desc": "Native translation.",
        "patient.loading": "Loading patient details...",
        "patient.not_found": "Patient not found",
        "patient.gender_unspecified": "Gender not specified",
        "patient.unknown_city": "Unknown City",
        "patient.edit_profile": "Edit Profile",
        "patient.recent_records": "Recent Health Records",
        "patient.table.date": "Date",
        "patient.table.bp": "BP",
        "patient.table.glucose": "Glucose",
        "patient.table.mood": "Mood",
        "patient.no_records": "No health records yet.",
        "patient.medications": "Medications",
        "patient.active": "Active",
        "patient.no_active_meds": "No active medications.",
        "patient.upcoming_visits": "Upcoming Visits",
        "patient.routine_visit": "Routine Visit",
        "patient.no_upcoming": "No upcoming visits.",
        "patient.assigned_carer": "Assigned Carer",
        "patient.verified_pro": "Verified Professional",
        "patient.assigning_carer": "Assigning a carer...",
        "patient.matching": "Our team is matching a carer.",
        "patient.modal.title": "Edit Patient Profile",
        "patient.modal.name": "Name",
        "patient.modal.dob": "Date of Birth",
        "patient.modal.gender": "Gender",
        "patient.modal.gender_select": "Select Gender",
        "patient.modal.gender_male": "Male",
        "patient.modal.gender_female": "Female",
        "patient.modal.gender_other": "Other",
    },
    my: {
        "profile.title": "ပရိုဖိုင် ဆက်တင်များ",
        "profile.subtitle": "သင့်အကောင့်အချက်အလက်များကို စီမံခန့်ခွဲပါ။",
        "profile.photo": "သင့်ဓာတ်ပုံ",
        "profile.change": "ပြောင်းလဲမည်",
        "profile.delete": "ဖျက်မည်",
        "profile.name": "အမည်အပြည့်အစုံ",
        "profile.email": "အီးမေးလ်",
        "profile.language": "ဘာသာစကား",
        "profile.save": "သိမ်းဆည်းမည်",
        "profile.signout": "ထွက်မည်",
        "profile.signout_desc": "ဤစက်မှ အကောင့်ထွက်ပါ။",
        "profile.role": "အခန်းကဏ္ဍ",
        "profile.joined": "စတင်ဝင်ရောက်သည့်ရက်",
        "nav.dashboard": "ပင်မစာမျက်နှာ",
        "nav.patients": "လူနာများ",
        "nav.chat": "စကားပြောရန်",
        "nav.schedule": "အချိန်ဇယား",
        "nav.profile": "ပရိုဖိုင်",
        "nav.overview": "မိသားစု",
        "nav.appointments": "ချိန်းဆိုမှုများ",
        "nav.reports": "အစီရင်ခံစာများ",
        "nav.services": "ဝန်ဆောင်မှုများ",
        "nav.view_profile": "ပရိုဖိုင်ကြည့်ရန်",
        "nav.sign_out": "ထွက်မည်",
        "chat.search": "ဆက်သွယ်သူများကို ရှာဖွေပါ...",
        "chat.no_connections_title": "ဆက်သွယ်ရန် မရှိသေးပါ",
        "chat.no_connections_desc": "မိသားစုဝင်နှင့် ဆက်စပ်ထားသော ပြုစုစောင့်ရှောက်သူ ရရှိသည်နှင့် အတူရှေ့တွင် ပေါ်လာပြီး စကားပြောနိုင်ပါသည်။",
        "chat.select_prompt": "စကားစတင်ရန် ဆက်သွယ်သူကို ရွေးပါ",
        "chat.online": "အွန်လိုင်း",
        "chat.type_message": "စာကို ရိုက်ထည့်ပါ...",
        "chat.video": "ဗီဒီယို",
        "schedule.empty": "ချိန်းဆိုထားသော အချိန်ဇယားများ မရှိသေးပါ။",
        "common.loading": "ခေတ္တစောင့်ပါ...",
        "common.error": "အမှားအယွင်းဖြစ်ပေါ်နေသည်",
        "carer.specialty": "ကျွမ်းကျင်မှု",
        "carer.experience": "လုပ်သက်အတွေ့အကြုံ (နှစ်)",
        "carer.verified": "အတည်ပြုပြီးသော ပြုစုစောင့်ရှောက်သူ",
        "carer.pending": "အတည်ပြုချက် စောင့်ဆိုင်းနေသည်",
        "carer.title": "ကျွမ်းကျင် ပြုစုစောင့်ရှောက်သူ",
        "patients.search_placeholder": "လူနာများကို ရှာဖွေပါ...",
        "patients.none_assigned": "တာဝန်ယူရသော လူနာများ မရှိသေးပါ",
        "patients.contact_admin": "အုပ်ချုပ်သူအား ဆက်သွယ်၍ လူနာများကို ချတ်ထားရန် တင်ပြပါ။",
        "patients.no_match": "ကိုက်ညီသော လူနာများ မရှိပါ",
        "patients.patient": "လူနာ",
        "patients.location": "တည်နေရာ",
        "patients.records_meds": "မှတ်တမ်းများ နှင့် ဆေးများ",
        "patients.records": "မှတ်တမ်း",
        "patients.meds": "ဆေးများ",
        "carer.dashboard.patients": "လူနာများ",
        "carer.dashboard.records": "မှတ်တမ်းများ",
        "carer.dashboard.visits": "လည်ပတ်မှုများ",
        "carer.dashboard.my_patients": "ကိုယ်တာဝန်ယူသော လူနာများ",
        "carer.dashboard.view_all": "အားလုံးကို ကြည့်ရန်",
        "carer.dashboard.quick_actions": "လျင်မြန်လုပ်ဆောင်မှုများ",
        "carer.dashboard.log_vitals": "ကျန်းမာရေးချက်များ မှတ်တမ်းတင်",
        "carer.dashboard.schedule": "အချိန်ဇယား",
        "schedules.upcoming": "မကြာမီ",
        "schedules.calendar": "ပြက္ခဒိန်",
        "schedules.history": "အတိတ်",
        "schedules.no_upcoming": "မကြာမီ အချိန်ဇယား မရှိပါ",
        "schedules.no_history": "မှတ်တမ်း မရှိပါ",
        "schedules.none_for_date": "ဤရက်တွင် ချိန်းဆိုထားသော လည်ပတ်မှု မရှိပါ။",
        "reports.title": "ဒစ်ဂျစ်တယ် အစီရင်ခံစာများ",
        "reports.filter.all": "အစီရင်ခံစာအားလုံး",
        "reports.filter.weekly": "အ tuần စုစည်းခြင်းများ",
        "reports.empty.title": "အစီရင်ခံစာ မရှိပါ",
        "reports.empty.desc": "သင့်တွင် အစီရင်ခံစာ မရှိသေးပါ။",
        "family.core.title": "အဓိက Plan အင်္ဂါရပ်များ",
        "family.core.subtitle": "၁ လ ၁,၀၀၀ ဘတ် စရိတ်တွင် ပါ၀င်ပါသည်။",
        "family.feature.health_monitor": "ကျန်းမာရေး စောင့်ကြည့်မှု",
        "family.feature.health_monitor_desc": "အသက်ရှူနှုန်းများနှင့် အချက်အလက်များကို လိုက်နာပါ။",
        "family.feature.view": "ကြည့်ရန်",
        "family.feature.reminders": "သတိပေးချက်များ",
        "family.feature.reminders_desc": "နေ့စဉ် ဆေး သုံးခြင်း reminders များကို လိုက်နာပါ။",
        "family.feature.schedule": "အချိန်ဇယား",
        "family.feature.reports": "အစီရင်ခံစာများ",
        "family.feature.reports_desc": "အပတ်စဉ် စုစည်းချက်များ",
        "family.feature.chat": "ပြုစုစောင့်ရှောက်မှု စကားဝိုင်း",
        "family.feature.chat_desc": "ပြုစုစောင့်ရှောက်သူနှင့် စကားပြောပါ",
        "family.feature.message": "စာပို့ရန်",
        "family.feature.checkups": "စစ်ဆေးမှုများ",
        "family.feature.checkups_desc": "အိမ်လည်ပတ်မှုများ စောင့်ကြည့်",
        "family.feature.settings": "ဆက်တင်များ",
        "family.feature.burmese_ui": "မြန်မာဘာသာ UI",
        "family.feature.burmese_ui_desc": "စွမ်းဆောင်ရည်မြင့် ဘာသာပြန်",
        "patient.loading": "လူနာ အချက်အလက်များကို ထည့်သွင်းနေသည်...",
        "patient.not_found": "လူနာကို မတွေ့ပါ",
        "patient.gender_unspecified": "လင်္ဂ အတည်မပြုရသေး",
        "patient.unknown_city": "မသိသောမြို့",
        "patient.edit_profile": "ပရိုဖိုင် ပြင်ဆင်ရန်",
        "patient.recent_records": "မကြာမီ ကျန်းမာရေး မှတ်တမ်းများ",
        "patient.table.date": "ရက်စွဲ",
        "patient.table.bp": "သွေးပေါင်",
        "patient.table.glucose": "သကြား",
        "patient.table.mood": "ခံစားချက်",
        "patient.no_records": "အချက်အလက်မှတ်တမ်း မရှိသေးပါ",
        "patient.medications": "ဆေးဝါးများ",
        "patient.active": "လက်ရှိအသုံး",
        "patient.no_active_meds": "အသုံးပြုဆေး မရှိပါ",
        "patient.upcoming_visits": "လာမည့် လည်ပတ်မှုများ",
        "patient.routine_visit": "ပုံမှန် လည်ပတ်မှု",
        "patient.no_upcoming": "လာမည့် လည်ပတ်မှု မရှိပါ",
        "patient.assigned_carer": "တာဝန်ယူ ပြုစုစောင့်ရှောက်သူ",
        "patient.verified_pro": "အတည်ပြုပြီးသော ပရော်ဖက်ရှင်နယ်",
        "patient.assigning_carer": "ပြုစုစောင့်ရှောက်သူ ခန့်အပ်နေသည်...",
        "patient.matching": "ကျွန်ုပ်တို့အသင်းက ပြုစုစောင့်ရှောက်သူကို တင်ပြနေပါသည်။",
        "patient.modal.title": "လူနာ ပရိုဖိုင် ပြင်ဆင်ရန်",
        "patient.modal.name": "အမည်",
        "patient.modal.dob": "မွေးသက္ကရာဇ်",
        "patient.modal.gender": "လင်္ဂ",
        "patient.modal.gender_select": "Gender ရွေးချယ်ပါ",
        "patient.modal.gender_male": "အထီး",
        "patient.modal.gender_female": "အမ",
        "patient.modal.gender_other": "အခြား",
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>(() => {
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('kera-language') as Language | null;
            return saved ?? 'en';
        }
        return 'en';
    });

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('kera-language', lang);
    };

    const t = (key: string): string => {
        return (translations[language] as Record<string, string>)[key] ?? key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
